version: '3'
networks:
  default:
    name: wat
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/testing

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
  # configure minio on startup (create buckets, etc)
  # inspired by https://github.com/minio/minio/issues/4769
  # and         https://gist.github.com/haxoza/22afe7cc4a9da7e8bdc09aad393a99cc
  minio_init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc mb   minio/configs;
      /usr/bin/mc policy set public minio/configs;
      /usr/bin/mc cp --recursive /configs/ minio/configs/ ;
      exit 0;
      "
    volumes:
      - ./configs:/configs/data/hydrographscaler
  hydro-scalar:
    depends_on: 
      - minio_init
      - cache
    build: .
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_S3_REGION=us-east-1
      - AWS_S3_BUCKET=configs
      - S3_MOCK=True
      - S3_BUCKET=configs
      - S3_ENDPOINT=minio:9000
      - S3_DISABLE_SSL=True
      - S3_FORCE_PATH_STYLE=True
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./:/workspaces
volumes:
  cache:
    driver: local